VERSION_NAME=0.1.0-alpha
GROUP=com.github.tlozovyi.week-view-compose

org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true

kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.mpp.androidGradlePluginCompatibility.nowarn=true
kotlin.mpp.androidSourceSetLayoutV2AndroidStyleDirs.nowarn=true
kotlin.apple.xcodeCompatibility.nowarn=true
